export const authConstants = {
  LOGIN_REQUEST: "LOGIN_REQUEST",
  LOGIN_FAILURE: "LOGIN_FAILURE",
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGOUT_REQUEST: "LOGOUT_REQUEST",
  LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
  LOGOUT_FAILURE: "LOGOUT_FAILURE",
  SIGNUP_SUCCESS: "SIGNUP_SUCCESS",
};

export const categoryConstants = {
  GET_ALL_REQUEST: "GET_ALL_REQUEST",
  GET_ALL_SUCCESS: "GET_ALL_SUCCESS",
  GET_ALL_FAILURE: "GET_ALL_FAILURE",
  ADD_NEW_REQUEST: "ADD_NEW_REQUEST",
  ADD_NEW_SUCCESS: "ADD_NEW_SUCCESS",
  ADD_NEW_FAILURE: "ADD_NEW_FAILURE",
};

export const productConstants = {
  GET_ALL_DATA_REQUEST: "GET_ALL_DATA_REQUEST",
  GET_ALL_DATA_SUCCESS: "GET_ALL_DATA_SUCCESS",
  GET_ALL_DATA_FAILURE: "GET_ALL_DATA_FAILURE",
};

export const userConstansts = {
  GET_USER_SUCCESS: "GET_USER_SUCCESS",
};

export const orderConstants = {
  GET_ORDER_SUCCESS: "GET_ORDER_SUCCESS",
};
